services:
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - VM_ORCHESTRATOR_URL=http://vm-orchestrator:8084
    depends_on:
      - vm-orchestrator
    networks:
      - avmo-network
    restart: unless-stopped

  vm-orchestrator:
    build:
      context: ./backend/vm-orchestrator
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8084
      - DB_CONNECTION_STRING=mongodb://mongo:27017/vms
      - JWT_SECRET=your_jwt_secret_key_here
    depends_on:
      - mongo
    networks:
      - avmo-network
    privileged: true  # Needed for virtualization
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - avmo-network
    restart: unless-stopped

networks:
  avmo-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
