version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=debug
      - PORT=3000
    command: ["node", "debug-server.js"]
    networks:
      - shaydz-network

  app-catalog:
    build: ./app-catalog
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=debug
      - PORT=3000
    command: ["node", "debug-server.js"]
    networks:
      - shaydz-network

  vm-orchestrator:
    build: ./vm-orchestrator
    ports:
      - "3003:5000"
    environment:
      - FLASK_ENV=debug
      - FLASK_DEBUG=1
    command: ["python3", "debug-orchestrator.py"]
    networks:
      - shaydz-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=debug
      - AUTH_SERVICE_URL=http://auth-service:3000
      - APP_CATALOG_URL=http://app-catalog:3000
      - VM_ORCHESTRATOR_URL=http://vm-orchestrator:5000
    depends_on:
      - auth-service
      - app-catalog
      - vm-orchestrator
    networks:
      - shaydz-network

networks:
  shaydz-network:
    driver: bridge
