//
//  ContentView.swift
//  ShaydZ-AVMo
//
//  Generated by iOS Integration Tool
//

import SwiftUI


struct ContentView: View {
    @StateObject private var authViewModel = AuthenticationViewModel()
    @StateObject private var appCatalogViewModel = AppCatalogViewModel()
    
    var body: some View {
        NavigationView {
            if authViewModel.isAuthenticated {
                AppCatalogView()
                    .environmentObject(appCatalogViewModel)
            } else {
                LoginView()
                    .environmentObject(authViewModel)
            }
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
