//
//  Models.swift
//  ShaydZ-AVMo
//
//  Generated by iOS Integration Tool
//

import Foundation

struct User: Codable {
    let id: String
    let username: String
    let email: String
    let isActive: Bool
}

struct App: Codable {
    let id: String
    let name: String
    let description: String
    let category: String
    let iconURL: String?
    let isInstalled: Bool
}

struct VirtualMachine: Codable {
    let id: String
    let name: String
    let status: VMStatus
    let cpuCount: Int
    let memoryMB: Int
}

enum VMStatus: String {
    case stopped
    case running
    case paused
    case error
}
