//
//  VirtualMachineViewModel.swift
//  ShaydZ-AVMo
//
//  Generated by iOS Integration Tool
//

import Foundation
import SwiftUI
import Combine

class VirtualMachineViewModel: ObservableObject {
    private let networkService = NetworkService.shared
    @Published var isLoading: Bool = false
    @Published var errorMessage: String? = nil
    
    private var cancellables = Set<AnyCancellable>()

    private func handleError(_ error: Error) {
        DispatchQueue.main.async { [weak self] in
            self?.isLoading = false
            self?.errorMessage = error.localizedDescription
        }
    }
}
